// Code generated by protoc-gen-go. DO NOT EDIT.
// source: client.proto

package hpclient

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Client struct {
	Public               string   `protobuf:"bytes,1,opt,name=public,proto3" json:"public,omitempty"`
	Private              string   `protobuf:"bytes,2,opt,name=private,proto3" json:"private,omitempty"`
	Id                   uint32   `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	Nickname             string   `protobuf:"bytes,4,opt,name=nickname,proto3" json:"nickname,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Client) Reset()         { *m = Client{} }
func (m *Client) String() string { return proto.CompactTextString(m) }
func (*Client) ProtoMessage()    {}
func (*Client) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{0}
}

func (m *Client) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Client.Unmarshal(m, b)
}
func (m *Client) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Client.Marshal(b, m, deterministic)
}
func (m *Client) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Client.Merge(m, src)
}
func (m *Client) XXX_Size() int {
	return xxx_messageInfo_Client.Size(m)
}
func (m *Client) XXX_DiscardUnknown() {
	xxx_messageInfo_Client.DiscardUnknown(m)
}

var xxx_messageInfo_Client proto.InternalMessageInfo

func (m *Client) GetPublic() string {
	if m != nil {
		return m.Public
	}
	return ""
}

func (m *Client) GetPrivate() string {
	if m != nil {
		return m.Private
	}
	return ""
}

func (m *Client) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Client) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func init() {
	proto.RegisterType((*Client)(nil), "hpclient.Client")
}

func init() { proto.RegisterFile("client.proto", fileDescriptor_014de31d7ac8c57c) }

var fileDescriptor_014de31d7ac8c57c = []byte{
	// 125 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x49, 0xce, 0xc9, 0x4c,
	0xcd, 0x2b, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0xc8, 0x28, 0x80, 0xf0, 0x95, 0xd2,
	0xb8, 0xd8, 0x9c, 0xc1, 0x2c, 0x21, 0x31, 0x2e, 0xb6, 0x82, 0xd2, 0xa4, 0x9c, 0xcc, 0x64, 0x09,
	0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x28, 0x4f, 0x48, 0x82, 0x8b, 0xbd, 0xa0, 0x28, 0xb3, 0x2c,
	0xb1, 0x24, 0x55, 0x82, 0x09, 0x2c, 0x01, 0xe3, 0x0a, 0xf1, 0x71, 0x31, 0x65, 0xa6, 0x48, 0x30,
	0x2b, 0x30, 0x6a, 0xf0, 0x06, 0x31, 0x65, 0xa6, 0x08, 0x49, 0x71, 0x71, 0xe4, 0x65, 0x26, 0x67,
	0xe7, 0x25, 0xe6, 0xa6, 0x4a, 0xb0, 0x80, 0x95, 0xc2, 0xf9, 0x49, 0x6c, 0x60, 0x8b, 0x8d, 0x01,
	0x01, 0x00, 0x00, 0xff, 0xff, 0x71, 0x8b, 0xdb, 0xa1, 0x88, 0x00, 0x00, 0x00,
}
